name: hawk_fab_menu
description: A floating action button menu that will pop up small fabs on top
version: 0.0.1
homepage: https://github.com/arnold-parge/hawk_fab_menu

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
